dist: bionic
env:
    global:
    -   GIT_NAME: Dead-Hosts
    -   GIT_EMAIL: dead-hosts@outlook.com
    -   GIT_BRANCH: master
    -   secure: EqyvH5DdR0QX9BFfjbvtcFwGsDbuwiaq3SglT1F8ymXPqNvEOcIgYObomsYyAe4SSJ3fHN3f8xwcA6qSpnqQFX+/THfEJ8EIfVM7r0rB2i0C+CvNoX42V57rY64YdolKzUa5ytwo5dPMVpDne8vr4xUajZtvj99DJOS5bMLjLfUvZ4RUMP4BtyNMt+gCKcPhdsFK3bWr/3hasnqDgP17eBD7H9JQ0AFo7usE+jRYsFaU1sGNxX3zYZ9mma4Zm8KGyQuEPU5VJ6JrJNmLID9Rl7E2kHI88o1oGqLNZIVugVidF/+XxeEcQVH4DZVYrlM6NfoI+EQza8wi6UFAwnoY2qsJCCud0p21vO/94peWYmBMaP8p0PYM+dFdgacpjEY2Az2/ALr3P3PbjWEgacMcS1v5pHqi/rkIIzb6Fa9D9U0UMLOzS2kFdK1U59roy/ncvwDQX5Yo8vjDjH2Ye9TojsTeibQu0R+rmlw0T254yyBfsELf8uoMF5FiR/xy1zCTX47IaW343O92dI83tEq35+N49Q/Xu9FapxTJc/w4gbMRwjAGstf2T7pTmqphoScfvdRU+TrbQy5+Tvf1+jgSCVg83gZz+psvs3Z991kdeZFQPdIMGeq/0tne224tsR3PIEf/0IKQ5+WUH3s166knF/ZWCNwUn+lQ1COD2ZTD+kc=
    -   PYTHON_VERSION: 3.7.5
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- source activate launcher-environment
- python -VV
- pip --version
- pip install --upgrade dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: change
        recipients:
        - dead-hosts@outlook.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
